name: Update Economic Calendar Data

on:
  schedule:
    # Exécute le workflow tous les lundis à 05:00 UTC (ce qui correspond au début de journée en Europe)
    - cron: '0 5 * * 1'
  # Permet de lancer manuellement ce workflow depuis l'onglet Actions de GitHub
  workflow_dispatch:

jobs:
  update-data:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Run update script
        run: python database_updater.py

      - name: Commit and push if changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add webapp/journal_v2.html
          # Vérifie s'il y a des changements à commiter
          if git diff --staged --quiet; then
            echo "No changes to commit."
          else
            git commit -m "Automated update of economic calendar data"
            git push
          fi
