name: Update Economic Calendar Data

on:
  schedule:
    # S'exécute à 02:00 UTC tous les dimanches.
    # '0 2 * * 0' est un format cron : minute heure jour(mois) mois jour(semaine)
    - cron: '0 2 * * 0'
  # Permet aussi de lancer le workflow manuellement depuis l'onglet Actions de GitHub
  workflow_dispatch:

jobs:
  update-data:
    runs-on: ubuntu-latest

    steps:
      # 1. Récupère le code de votre dépôt
      - name: Check out repository
        uses: actions/checkout@v3

      # 2. Met en place l'environnement Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x' # Utilise la dernière version de Python 3

      # 3. Installe les dépendances nécessaires
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      # 4. Exécute le script de mise à jour
      - name: Run update script
        run: python database_updater.py

      # 5. Commit et Push les modifications (si le fichier a changé)
      - name: Commit and push if there are changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add webapp/index.html
          # Ne commit que s'il y a des changements à commiter
          git diff --staged --quiet || git commit -m "Mise à jour automatique des données du calendrier économique"
          git push
